### ISSUE TITLE
Multiple answers sharing the same text value can cause scoring issues

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/last-chance-cadet-materia-widget#35]
An instructor had two answer tokens with the same string value, but the score module is using a randomly generated asset ID to match responses with questions and answers in the logs, causing a pair of questions sharing the same answer text to be incorrectly marked wrong if the student uses the _other_ answer token to perform the match. We've probably solved this problem in Matching, so we should verify what changes need to happen to the score module (or qset generation) to correct this.

**Comment by cayb0rg** [comment]
The player was sending the audio asset value even when there were no audio assets, so the score_module would compare the audio strings instead of the answer text. This issue was indeed fixed in Matching, so I copied those changes to this widget. (the [commit](https://github.com/ucfopen/last-chance-cadet-materia-widget/commit/ef6317fac4eab348e182c48947eea83b3bc0c434))
